### ISSUE TITLE
Update /utils/tests.py

### ISSUE THREAD

**Issue by mtarsel** [mtarsel/ContainerAnalysis#7]
See 4cffb186e0416a9a8c37d135615

This is helpful to test a single application rather than waiting for all of them to finish and output. The code in tests.py is out-dated and needs to be changed to better utilize more functions instead of copy code.

This issue will be marked complete once it is possible to test a single application with proper output.

**Comment by mtarsel** [comment]
After #20 is closed, this task should consider a new commandline input called test:
```bash
python3 get-image-info.py user.yaml  --test app_name
```

**Comment by 1ethanhansen** [comment]
I'm working on this one now

**Comment by 1ethanhansen** [comment]
I think it would be possible to just make it a --test option like mentioned above, without even needed a full file for tests.py. It can just make the app_list equal to one app when it gets run.

**Comment by 1ethanhansen** [comment]
Found a bug while working on this: in parse_index_yaml the keywords were saved from app-to-app. This wasn't a problem unless we found an app where there weren't keyword in the index.yaml file. In those cases the keywords from the previous app were also saved as the keywords for the app with no keywords in the index.yaml, like ibm-integration-bus-dev, which has no keywords in either the index.yaml or its Chart.yaml. Fixed by clearing keywords run-to-tun

**Comment by mtarsel** [comment]
This is about to be removed in the next big merge. Standby

**Comment by 1ethanhansen** [comment]
> This is about to be removed in the next big merge. Standby

The bug or the whole issue?

**Comment by mtarsel** [comment]
I tried to keep the git tree clean but there is still a merge commit. The real juicy info is in 2d6dfea72006d4251a5e, which says, "tests.py no longer exists since the way to test a single App
is in dire need of update. This file was riddled with old, repetitive
code and therefore has been removed."

**Comment by mtarsel** [comment]
In order for this change to be merged and the issue closed, there needs to be travis code included in the commit.
