### ISSUE TITLE
Gather more information about containers for cross-validation

### ISSUE THREAD

**Issue by 1ethanhansen** [mtarsel/ContainerAnalysis#9]
eg: Crawl git repos parsing READMEs

from [The wiki](https://github.com/mtarsel/ContainerAnalysis/wiki)

**Comment by mtarsel** [comment]
In the results.csv there is sometimes differences between the architecture information gathered from Charts.yaml vs. values.yaml.

This task is for creating some way let the user know there is a difference in architectures, but also ensure that our project was accurate in crawling info from dockerhub. I would recommend closing #8 first since this will clean up most of the output.
